require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/Output:
  Enabled: false
