require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/Output:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
